# Generated by Django 3.0.8 on 2020-11-08 17:58

import datetime
from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', smartfields.fields.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=400)),
                ('subhead', models.TextField()),
                ('button_bool', models.BooleanField(default=False)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('message', models.TextField()),
                ('number', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Head_footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('favicon', models.FileField(upload_to='svg')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', smartfields.fields.ImageField(upload_to='pics')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('Price_display', models.BooleanField(default=False)),
                ('specification', models.TextField()),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('read_more', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=100)),
                ('video_thumbnail', smartfields.fields.ImageField(upload_to='pics')),
                ('videofile', models.FileField(null=True, upload_to='videos')),
                ('Display_onpage', models.BooleanField(default=False)),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vision_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_text', models.CharField(blank=True, max_length=100)),
                ('vision_head', models.CharField(blank=True, max_length=100)),
                ('vision_subhead', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
