# Generated by Django 3.0.8 on 2020-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
            ],
        ),
    ]
