# Generated by Django 3.0.8 on 2020-11-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0002_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='para3',
        ),
    ]
