# Generated by Django 3.0.8 on 2020-11-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0003_remove_about_us_para3'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='contact_head',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='head_footer',
            name='prod_head',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
