# Generated by Django 3.0.8 on 2020-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0005_remove_customer_detail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='my_email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
