# Generated by Django 3.0.8 on 2020-11-10 04:18

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0006_head_footer_my_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision_mission',
            name='vision_parallax_img',
            field=smartfields.fields.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
