# Generated by Django 3.0.8 on 2020-11-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0007_vision_mission_vision_parallax_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='head_footer',
            name='phn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
