# Generated by Django 3.0.8 on 2020-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0008_auto_20201110_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='read_more',
            field=models.TextField(blank=True),
        ),
    ]
