# Generated by Django 3.0.8 on 2020-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0009_auto_20201110_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='read_more_btn',
            field=models.BooleanField(default=False),
        ),
    ]
