# Generated by Django 3.0.8 on 2020-11-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0010_service_read_more_btn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vision_mission',
            old_name='vision_head',
            new_name='vision_name',
        ),
    ]
