# Generated by Django 3.0.8 on 2020-11-10 07:52

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0011_auto_20201110_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='contact_parallax_img',
            field=smartfields.fields.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
