# Generated by Django 3.0.8 on 2020-11-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0012_head_footer_contact_parallax_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo_Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_desc', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
            ],
        ),
    ]
