# Generated by Django 3.0.8 on 2020-11-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0014_product_detail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='Logo_img_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='head_footer',
            name='logo_name_display',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
