# Generated by Django 3.0.8 on 2020-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0015_auto_20201111_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_video',
            name='video_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
