# Generated by Django 3.0.8 on 2020-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0016_upload_video_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_footer',
            name='video_head',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
