# Generated by Django 3.0.8 on 2020-11-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_content', '0019_remove_head_footer_gif_404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_video',
            old_name='video',
            new_name='video_name',
        ),
    ]
